name: Build and test app

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        # temurin LTS is pre-cached on runners
        # https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'

    - name: Gradle check
      run: ./gradlew check --no-daemon

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: outputs
        path: app/build/outputs

