name: Build and test app

on:
  push:
    branches: [ '*' ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        # temurin LTS is pre-cached on runners
        # https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Hosted-Tool-Cache
        distribution: 'temurin'
        java-version: '17'

    # prevent supply chain attacks from replacing our gradle with malicious code
    # https://github.com/gradle/wrapper-validation-action#readme
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Gradle check
      run: ./gradlew check --no-daemon

    - name: Archive build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: outputs
        path: app/build/outputs

